name: Publish image to Docker hub
on:
    
    push:
                   

  

jobs:
    publich_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run:
                ls
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_HUB_USERNAME}}
                password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

            - name: build image
              run: |
                IMAGE_TAG=$(git rev-parse --short HEAD)
                echo $IMAGE_TAG  # Use commit hash as a unique tag
                docker build -t edwinasweeney/modelbuild:$IMAGE_TAG .
                docker images
            - name: push image to docker hub
              run: |
                docker push edwinasweeney/modelbuild:$IMAGE_TAG
               