 
name: mlModel1 thirdEx
on: 
   
    workflow_dispatch:  

jobs:
    echo:
        runs-on: self-hosted
        steps:
            - name: Show the trigger 
              run: |
               echo "this is the start"
               echo "this is another start"

            - name: Checkout Repository
              uses: actions/checkout@v4

            
               
            - name: Run New Container
              run: |
               docker pull edwinasweeney/modelbuild:latest
               docker run -d --name edml-model-container edwinasweeney/modelbuild:latest