 
name: mlModel1 thirdEx
on:
  repository_dispatch:
    types: [docker-hub-push] 
  workflow_dispatch:  

jobs:
    echo:
        runs-on: self-hosted
        steps:
            - name: Get latest Docker Hub tag
              run: |
                LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/your-dockerhub-username/your-repo/tags/?page_size=1" | jq -r '.results[0].name')
                  echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

            - name: Check for changes
              run: |
                       PREV_TAG=$(curl -s https://gist.githubusercontent.com/e-sweeney/40e0d7a802f6908031e02f9e0c4cfd7f/raw/238c856b6ecb3d1637b2f7302777f6e2ff5f87ee/docker-hub-latest-tag.txt  # Store previous tag in a GitHub Gist or secret storage
                        if [ "$LATEST_TAG" != "$PREV_TAG" ]; then
                            echo "New tag detected: $LATEST_TAG"
                            echo "$LATEST_TAG" > latest_tag.txt
                            curl -X POST -H "Authorization: token ${{ secrets.DEPLOY_ACCESS_TOKEN }}" \
                            -H "Accept: application/vnd.github.everest-preview+json" \
                                https://github.com/e-sweeney/mlModel/actions/workflows/thirdml.yml/dispatches \
                                    -d '{"ref":"main"}'
                            curl -X PUT -d "$LATEST_TAG" https://gist.githubusercontent.com/your-gist-url/raw  # Update stored tag
                        else
                              echo "No new image updates."
                        fi
        
        steps:
            - name: Show the trigger 
              run: |
               echo "this is the start"
               echo "this is another start"

            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Stop & Remove Old Container
              run: |
                docker stop edml-model-container || true
                docker rm edml-model-container || true
               
            - name: Run New Container
              run: |
               docker pull edwinasweeney/modelbuild:latest
               docker run -d --name edml-model-container edwinasweeney/modelbuild:latest