 
name: mlModel1 thirdEx
on:
  workflow_dispatch:  # Manual trigger via API
  

jobs:
    echo:
        runs-on: self-hosted
        steps:
          - name: Get Tag
            run: |
              GIST_URL="https://gist.githubusercontent.com/e-sweeney/40e0d7a802f6908031e02f9e0c4cfd7f/raw/238c856b6ecb3d1637b2f7302777f6e2ff5f87ee/docker-hub-latest-tag.txt"

              # Get the latest tag from Docker Hub
              # Fetch the list of tags from Docker Hub for your image repository
              TAGS=$(curl -s "https://hub.docker.com/v2/repositories/edwinasweeney/modelbuild/tags/" | jq -r '.results[].name')

              # Get the latest unique tag (e.g., the most recent commit hash or version)
              LATEST_TAG=$(echo "$TAGS" | sort -r | head -n 1)  # Sort tags in descending order and get the most recent one
              echo "Previous Gist Tag: $LATEST_TAG"
          
              # Get the previous tag from the Gist
              PREV_TAG=$(curl -s "$GIST_URL")
              echo "Previous Gist Tag: $PREV_TAG"

              # Compare tags and trigger workflow if there's a new image
              if [ "$LATEST_TAG" != "$PREV_TAG" ]; then
                  echo "New tag detected, this is it->: $LATEST_TAG"

                  # Update the Gist with the new tag
                  curl -X PATCH -H "Authorization: Bearer ${{ secrets.GIST_TOKEN }}" \
                            -d "{\"files\": {\"docker-hub-latest-tag.txt\": {\"content\": \"$LATEST_TAG\"}}}" \
                  "https://api.github.com/gists/40e0d7a802f6908031e02f9e0c4cfd7f"

                                
                    
                    curl -X POST \
                  -H "Authorization: token ${{ secrets.DEPLOY_ACCESS_TOKEN }}" \
                  -H "Accept: application/vnd.github.everest-preview+json" \
                      -d '{"ref":"main"}' \
                   https://api.github.com/repos/e-sweeney/mlModel/actions/workflows/thirdml.yml/dispatches


              else
                   echo "No new image updates."
              fi
        
          - name: Show the trigger 
            run: |
              echo "this is the start"
              echo "this is another start"

          - name: Checkout Repository
            uses: actions/checkout@v4

          #- name: Stop & Remove Old Container
          #  run: |
          #    docker stop edml-model-container || true
          #    docker rm edml-model-container || true
               
          #- name: Run New Container
          #  run: |
          #   docker pull edwinasweeney/modelbuild:latest
          #   docker run -d --name edml-model-container edwinasweeney/modelbuild:latest