 
name: mlModel1 thirdEx
on:
  repository_dispatch:
    types: [docker-hub-push] 
  workflow_dispatch:  

jobs:
    echo:
        runs-on: self-hosted
        steps:
            - name: Show the trigger 
              run: |
               echo "this is the start"
               echo "this is another start"

            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Stop & Remove Old Container
              run: |
                docker stop edml-model-container || true
                docker rm edml-model-container || true
               
            - name: Run New Container
              run: |
               docker pull edwinasweeney/modelbuild:latest
               docker run -d --name edml-model-container edwinasweeney/modelbuild:latest